/// Flutter icons FzIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FzIcons
///      fonts:
///       - asset: fonts/FzIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class FzIcons {
  FzIcons._();

  static const _kFontFam = 'FzIcons';
  static const _kFontPkg = null;

  static const IconData female_filled = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData certificate = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData feedback = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData female = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData privacy_policy = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData setting = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData university = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData danger = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData analysis = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData planner2_filled = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData male_filled = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData male = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings_filled = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData signup = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stack_filled = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData envelope = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData assignment = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData report = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData event = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData project = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exam = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData presentation = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData drag_indicator = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
