const Map<String, String> kCarriersList = {
  'U.S. Postal Service': 'usps',
  'Stamps.com': 'stamps_com',
  'FedEx': 'fedex',
  'UPS': 'ups',
  'DHL Express': 'dhl_express',
  'DHL ECommerce': 'dhl_global_mail',
  'Canada Post': 'canada_post',
  'Australia Post': 'australia_post',
  'First Mile': 'firstmile',
  'Asendia': 'asendia',
  'OnTrac': 'ontrac',
  'APC': 'apc',
  'Newgistics': 'newgistics',
  'Globegistics': 'globegistics',
  'RR Donnelley': 'rr_donnelley',
  'IMEX': 'imex',
  'Access Worldwide': 'access_worldwide',
  'Purolator Canada': 'purolator_ca',
  'Sendle': 'sendle'
};
